discord:
  # Discord Bot Token
  token: ""

  # ID of Discord Server to Monitor
  guild_id: ""

  # Category & Channel IDs
  event_category: ""
  archive_category: ""
  notification_channel: ""


# mastodon:
#   server: https://mastodon.social
#   username: my_user
#   password: secret
#   client_id: 1234
#   client_secret: secret2