discord:
  # Discord Bot Token
  token: ""

  # ID of Discord Server to Monitor
  guild_id: ""

  # Category & Channel IDs
  event_category: ""
  archive_category: ""
  notification_channel: ""

  # # Configure role selection
  # role_selection:
  # - title: "SELECTION TITLE"
  #   description: "SELECTION DESCRIPTION"
  #   discord_channel: ""
  #   roles:
  #   - name: Red
  #     color: "#f64c38"
  #   - name: Blue
  #     color: "#1a88ff"

# mastodon:
#   server: https://mastodon.social
#   username: my_user
#   password: secret
#   client_id: 1234
#   client_secret: secret2

# status_portal:
#   url: https://status.example.com

# # Feature flags can be used to
# # disable specific features
# features:
#   manage_event_channels: true
#   announce_events: true
#   recurring_events: true
#   role_selection: true
#   status_portal: false